#include "scripts/weapons/ShellEjectingWeapon.zs"
#include "scripts/weapons/Bolter.zs"
#include "scripts/weapons/AstartesShotgun.zs"
#include "scripts/weapons/HeavyBolter.zs"
#include "scripts/weapons/Volkite.zs"
#include "scripts/weapons/MissileLauncher.zs"
#include "scripts/weapons/Melta.zs"
#include "scripts/weapons/SternguardWeapon.zs"

#include "scripts/TrailedProjectile.zs"