#include "scripts/weapons/ShellEjectingWeapon.zs"
#include "scripts/weapons/Bolter.zs"
#include "scripts/weapons/AstartesShotgun.zs"
#include "scripts/weapons/HeavyBolter.zs"
#include "scripts/weapons/volkite.zs"
#include "scripts/weapons/MissileLauncher.zs"
#include "scripts/weapons/TrailedProjectile.zs"